<?php

namespace App\Support;

class EmailNotificationTemplateDefaults
{
    /**
     * @return array{
     *     subject_user?: string,
     *     body_user?: string,
     *     subject_admin?: string,
     *     body_admin?: string,
     *     auto_enable?: bool
     * }
     */
    public static function for(string $notificationType): array
    {
        return match ($notificationType) {
            EmailNotificationTypeRegistry::SIGNUP => [
                'subject_user' => 'Welcome to YogaFX, {user_name}',
                'subject_admin' => 'YogaFX signup completed: {user_email}',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>Welcome to YogaFX!</p>',
                    '<p>Your enrollment and password setup have been completed successfully. Your LMS account is now ready to use.</p>',
                    '<p>Your access tier: <strong>{access_tier_label}</strong></p>',
                    '<p>You can now log in to your YogaFX LMS account here:</p>',
                    '<p><a href="{login_url}">{login_url}</a></p>',
                    '<p>We are excited to have you begin your learning journey with YogaFX.</p>',
                    '<p>YogaFX Team</p>',
                ]),
                'body_admin' => implode('', [
                    '<p>Hi Admin,</p>',
                    '<p>A new student has completed the YogaFX signup process and their LMS account is now ready.</p>',
                    '<p>Student name: {user_name}</p>',
                    '<p>Student email: {user_email}</p>',
                    '<p>Access tier: {access_tier_label}</p>',
                    '<p>Registration date: {registration_date}</p>',
                    '<p>The student has completed enrollment and password creation, so they can now log in to the LMS normally.</p>',
                    '<p>Login URL:</p>',
                    '<p><a href="{login_url}">{login_url}</a></p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::RESET_PASSWORD => [
                'subject_user' => 'Reset your YogaFX password',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>We received a request to reset your YogaFX password.</p>',
                    '<p><a href="{reset_url}">Click here to reset your password</a></p>',
                    '<p>Your one-time password code: <strong>{otp}</strong></p>',
                    '<p>This link will expire in {reset_expiry_minutes} minutes.</p>',
                    '<p>If you did not request this, you can safely ignore this email.</p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::MODULE_COMPLETION => [
                'subject_user' => 'Module completed: {module_title}',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>You have completed <strong>{module_title}</strong>.</p>',
                    '<p>Module progress: {module_progress}</p>',
                    '<p>Current learning path progress: {course_progress}</p>',
                    '<p>Keep going from your dashboard: <a href="{dashboard_url}">{dashboard_url}</a></p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::ASSESSMENT_COMPLETE => [
                'subject_user' => 'Assessment completed: {assessment_title}',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>You have completed <strong>{assessment_title}</strong>.</p>',
                    '<p>Your latest score: <strong>{assessment_score}</strong></p>',
                    '<p>See your progress here: <a href="{result_url}">{result_url}</a></p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::ASSIGNMENT_REVIEW => [
                'subject_user' => 'Your assignment is under review',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>Your assignment submission for <strong>{assignment_type}</strong> has been received.</p>',
                    '<p>Our team is reviewing it now. We will email you again once the review is complete.</p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::ASSIGNMENT_APPROVED => [
                'subject_user' => 'Your YogaFX graduation requirements are complete',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>Congratulations! You have completed all graduation requirements.</p>',
                    '<p>You can access your certificate from your dashboard: <a href="{dashboard_url}">{dashboard_url}</a></p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::ASSIGNMENT_REJECTED => [
                'subject_user' => 'Assignment update: resubmission needed',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>Your submission for <strong>{assignment_type}</strong> needs revision before it can be approved.</p>',
                    '<p>Feedback: {feedback}</p>',
                    '<p>Please revisit your dashboard and upload an updated version when ready.</p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::CERTIFICATE_CREATED => [
                'subject_user' => 'Your YogaFX certificate is ready',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>Your certificate for <strong>{certificate_type}</strong> has been created.</p>',
                    '<p>Certificate file: {certificate_file_name}</p>',
                    '<p>You can check your student dashboard for the latest status.</p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::COURSE_COMPLETE => [
                'subject_user' => 'Learning path complete: {course_title}',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>You have completed your accessible YogaFX learning path: <strong>{course_title}</strong>.</p>',
                    '<p>Completion date: {completion_date}</p>',
                    '<p>Learning path progress: {course_progress}</p>',
                    '<p>Open your dashboard here: <a href="{dashboard_url}">{dashboard_url}</a></p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::REMINDER => [
                'subject_user' => 'We saved your place in YogaFX',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>We noticed you have not continued your YogaFX learning session since {last_activity_date}.</p>',
                    '<p>Return to your dashboard anytime: <a href="{dashboard_url}">{dashboard_url}</a></p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::WORKBOOK_SENT => [
                'subject_user' => 'Your workbook is ready: {lesson_title}',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>Your workbook for <strong>{lesson_title}</strong> is attached to this email.</p>',
                    '<p>Module: {module_title}</p>',
                    '<p>Workbook file: {workbook_file_name}</p>',
                    '<p>You can continue learning from your dashboard here: <a href="{dashboard_url}">{dashboard_url}</a></p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::PAYMENT_SUCCESS => [
                'subject_user' => '{payment_success_subject}: welcome to YogaFX, {user_name}',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>{payment_success_message}</p>',
                    '<p>Your invoice confirmation PDF is attached as <strong>{invoice_pdf_file_name}</strong>.</p>',
                    '<p>Invoice: <strong>{invoice_number}</strong></p>',
                    '<p>Payment reference: <strong>{payment_reference}</strong></p>',
                    '<p>Amount: <strong>{currency_code} {amount}</strong></p>',
                    '<p>Your next step is enrollment. Continue here:</p>',
                    '<p><a href="{enrollment_url}">{enrollment_url}</a></p>',
                    '<p>We are excited to welcome you into YogaFX.</p>',
                ]),
                'subject_admin' => 'YogaFX {payment_success_subject}: {user_email}',
                'body_admin' => implode('', [
                    '<p>{payment_success_admin_message}</p>',
                    '<p>Invoice PDF attached: <strong>{invoice_pdf_file_name}</strong></p>',
                    '<p>Student: <strong>{user_name}</strong> ({user_email})</p>',
                    '<p>Access tier: <strong>{access_tier_label}</strong></p>',
                    '<p>Invoice: <strong>{invoice_number}</strong></p>',
                    '<p>Payment reference: <strong>{payment_reference}</strong></p>',
                    '<p>Amount: <strong>{currency_code} {amount}</strong></p>',
                    '<p>Enrollment continuation:</p>',
                    '<p><a href="{enrollment_url}">{enrollment_url}</a></p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::CHECKOUT_PAYMENT_LINK => [
                'subject_user' => 'Complete your YogaFX payment: {package_title}',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>We have saved your registration for <strong>{package_title}</strong> ({access_tier_label}).</p>',
                    '<p>Amount due: <strong>{currency_code} {amount}</strong></p>',
                    '<p>You can finish your payment anytime using the link below — no need to fill in your details again:</p>',
                    '<p><a href="{payment_link_url}">{payment_link_url}</a></p>',
                    '<p>If you already completed this payment, you can safely ignore this email.</p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::ENROLLMENT_SUCCESS => [
                'subject_user' => 'Enrollment completed: your YogaFX signup is ready',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>Congratulations. Your enrollment for <strong>{access_tier_label}</strong> is complete.</p>',
                    '<p>Your next step is to create your password and finish signup here:</p>',
                    '<p><a href="{signup_url}">{signup_url}</a></p>',
                    '<p>Once that is done, your YogaFX LMS account will be ready to use.</p>',
                ]),
                'subject_admin' => 'YogaFX enrollment completed: {user_email}',
                'body_admin' => implode('', [
                    '<p>A student has completed the YogaFX enrollment step.</p>',
                    '<p>Student: <strong>{user_name}</strong> ({user_email})</p>',
                    '<p>Access tier: <strong>{access_tier_label}</strong></p>',
                    '<p>Next step signup URL:</p>',
                    '<p><a href="{signup_url}">{signup_url}</a></p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::INSTALLMENT_PAYMENT_SUCCESS => [
                'subject_user' => 'Your YogaFX installment payment was successful',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>We have received your installment payment for <strong>{package_title}</strong>.</p>',
                    '<p>Your invoice confirmation PDF is attached as <strong>{invoice_pdf_file_name}</strong>.</p>',
                    '<p>Payment amount: <strong>{currency_code} {payment_amount}</strong></p>',
                    '<p>Installments paid: {installments_paid_count} of {installment_count}</p>',
                    '<p>Remaining balance: <strong>{currency_code} {balance_due}</strong></p>',
                    '<p>Next due date: {next_due_at}</p>',
                ]),
                'subject_admin' => 'Installment payment success for {user_email}',
                'body_admin' => implode('', [
                    '<p>A successful installment payment has been recorded.</p>',
                    '<p>Invoice PDF attached: <strong>{invoice_pdf_file_name}</strong></p>',
                    '<p>Student: <strong>{user_name}</strong> ({user_email})</p>',
                    '<p>Package: <strong>{package_title}</strong></p>',
                    '<p>Tier: <strong>{tier_name}</strong></p>',
                    '<p>Invoice: <strong>{invoice_number}</strong></p>',
                    '<p>Payment amount: <strong>{currency_code} {payment_amount}</strong></p>',
                    '<p>Installments paid: {installments_paid_count} of {installment_count}</p>',
                    '<p>Remaining balance: <strong>{currency_code} {balance_due}</strong></p>',
                    '<p>Next due date: {next_due_at}</p>',
                    '<p>Grace deadline: {grace_deadline_at}</p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::INSTALLMENT_PAYMENT_FAILED => [
                'subject_user' => 'Your YogaFX installment payment needs attention',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>Your latest installment payment for <strong>{package_title}</strong> was not completed.</p>',
                    '<p>Expected payment amount: <strong>{currency_code} {payment_amount}</strong></p>',
                    '<p>Remaining balance: <strong>{currency_code} {balance_due}</strong></p>',
                    '<p>Next due date: {next_due_at}</p>',
                    '<p>Grace deadline: {grace_deadline_at}</p>',
                ]),
                'subject_admin' => 'Installment payment failed for {user_email}',
                'body_admin' => implode('', [
                    '<p>An installment payment failed and the subscription is now in grace period.</p>',
                    '<p>Student: <strong>{user_name}</strong> ({user_email})</p>',
                    '<p>Package: <strong>{package_title}</strong></p>',
                    '<p>Tier: <strong>{tier_name}</strong></p>',
                    '<p>Invoice: <strong>{invoice_number}</strong></p>',
                    '<p>Expected payment amount: <strong>{currency_code} {payment_amount}</strong></p>',
                    '<p>Installments paid: {installments_paid_count} of {installment_count}</p>',
                    '<p>Remaining balance: <strong>{currency_code} {balance_due}</strong></p>',
                    '<p>Next due date: {next_due_at}</p>',
                    '<p>Grace deadline: {grace_deadline_at}</p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::INSTALLMENT_OVERDUE_INACTIVE => [
                'subject_user' => 'Your YogaFX access is temporarily inactive',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>Your installment grace period for <strong>{package_title}</strong> has ended, so your YogaFX access is temporarily inactive.</p>',
                    '<p>Remaining balance: <strong>{currency_code} {balance_due}</strong></p>',
                    '<p>Next due date: {next_due_at}</p>',
                    '<p>Grace deadline: {grace_deadline_at}</p>',
                ]),
                'subject_admin' => 'Installment overdue: account inactive for {user_email}',
                'body_admin' => implode('', [
                    '<p>The installment grace deadline has passed and the student account is now inactive.</p>',
                    '<p>Student: <strong>{user_name}</strong> ({user_email})</p>',
                    '<p>Package: <strong>{package_title}</strong></p>',
                    '<p>Tier: <strong>{tier_name}</strong></p>',
                    '<p>Invoice: <strong>{invoice_number}</strong></p>',
                    '<p>Remaining balance: <strong>{currency_code} {balance_due}</strong></p>',
                    '<p>Next due date: {next_due_at}</p>',
                    '<p>Grace deadline: {grace_deadline_at}</p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::INSTALLMENT_PAYMENT_COMPLETED => [
                'subject_user' => 'Your installment payment is complete',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>Your installment plan for <strong>{package_title}</strong> has been fully paid.</p>',
                    '<p>Invoice: <strong>{invoice_number}</strong></p>',
                    '<p>Total installments paid: {installments_paid_count} of {installment_count}</p>',
                    '<p>Completion date: {payment_completed_at}</p>',
                    '<p>Your access remains available in your YogaFX account.</p>',
                ]),
                'subject_admin' => 'Installment fully paid for {user_email}',
                'body_admin' => implode('', [
                    '<p>An installment plan has been fully paid.</p>',
                    '<p>Student: <strong>{user_name}</strong> ({user_email})</p>',
                    '<p>Package: <strong>{package_title}</strong></p>',
                    '<p>Tier: <strong>{tier_name}</strong></p>',
                    '<p>Invoice: <strong>{invoice_number}</strong></p>',
                    '<p>Final payment amount: <strong>{currency_code} {payment_amount}</strong></p>',
                    '<p>Total installments paid: {installments_paid_count} of {installment_count}</p>',
                    '<p>Completed at: {payment_completed_at}</p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::ACCOMMODATION_BOOKING_CONFIRMED => [
                'subject_user' => 'Your booking at {hotel_name} is confirmed',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>Your booking at <strong>{hotel_name}</strong> has been confirmed.</p>',
                    '<p>Booking number: <strong>{booking_number}</strong></p>',
                    '<p>Room type: {room_type}</p>',
                    '<p>Check-in: {check_in_date}</p>',
                    '<p>Check-out: {check_out_date}</p>',
                    '<p>Nights: {nights}</p>',
                    '<p>Total paid: <strong>{currency_code} {total_amount}</strong></p>',
                    '<p>We look forward to hosting you.</p>',
                ]),
                'subject_admin' => 'New accommodation booking confirmed: {booking_number}',
                'body_admin' => implode('', [
                    '<p>A new accommodation booking has been confirmed.</p>',
                    '<p>Guest: <strong>{user_name}</strong> ({user_email})</p>',
                    '<p>Hotel: <strong>{hotel_name}</strong></p>',
                    '<p>Room type: {room_type}</p>',
                    '<p>Check-in: {check_in_date}</p>',
                    '<p>Check-out: {check_out_date}</p>',
                    '<p>Nights: {nights}</p>',
                    '<p>Total paid: <strong>{currency_code} {total_amount}</strong></p>',
                    '<p>Booking number: <strong>{booking_number}</strong></p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::ACCOMMODATION_INSTALLMENT_PAYMENT_FAILED => [
                'subject_user' => 'A payment for your booking at {hotel_name} did not go through',
                'body_user' => implode('', [
                    '<p>Hi {user_name},</p>',
                    '<p>Installment {failed_installment_number} of {installment_count} for your booking at <strong>{hotel_name}</strong> was not completed.</p>',
                    '<p>Booking number: <strong>{booking_number}</strong></p>',
                    '<p>Room type: {room_type}</p>',
                    '<p>Amount that failed to charge: <strong>{currency_code} {failed_amount}</strong></p>',
                    '<p>PayPal will automatically try again. Next attempt: {next_due_at}</p>',
                    '<p>Your booking remains confirmed — no action is needed unless the payment keeps failing.</p>',
                ]),
                'subject_admin' => 'Accommodation installment payment failed: {booking_number}',
                'body_admin' => implode('', [
                    '<p>An accommodation installment payment attempt failed.</p>',
                    '<p>Guest: <strong>{user_name}</strong> ({user_email})</p>',
                    '<p>Hotel: <strong>{hotel_name}</strong></p>',
                    '<p>Room type: {room_type}</p>',
                    '<p>Booking number: <strong>{booking_number}</strong></p>',
                    '<p>Failed installment: {failed_installment_number} of {installment_count}</p>',
                    '<p>Failed amount: <strong>{currency_code} {failed_amount}</strong></p>',
                    '<p>Next due date: {next_due_at}</p>',
                    '<p>The booking remains confirmed regardless of how many attempts fail.</p>',
                ]),
                'auto_enable' => true,
            ],
            EmailNotificationTypeRegistry::IRREGULAR_ACTIVITY_SUSPENDED => [
                'subject_user' => 'Your YogaFX account has been temporarily suspended',
                'body_user' => implode('', [
                    '<p>Dear Student,</p>',
                    '<p>Please be advised that we have detected irregular activity on the platform and for security purposes, the account is temporarily blocked.</p>',
                    '<p>Please contact us some more support for more information and assistance.</p>',
                    '<p>Thank you,<br>YogaFX IT Support</p>',
                ]),
                'subject_admin' => 'Student suspended for irregular activity: {user_email}',
                'body_admin' => implode('', [
                    '<p>A student account has been suspended after repeated irregular lesson activity.</p>',
                    '<p>Student: <strong>{user_name}</strong> ({user_email})</p>',
                    '<p>Latest lesson: <strong>{lesson_title}</strong></p>',
                    '<p>Irregular activity count: <strong>{irregular_activity_count}</strong></p>',
                    '<p>The student can contact support using the configured WhatsApp and email channels.</p>',
                ]),
                'auto_enable' => true,
            ],
            default => [],
        };
    }
}
